#ifndef PCB_PIN_MAP_H
#define PCB_PIN_MAP_H

#include "stm32f4xx_hal.h"

// PORTA pins
#define DI_WAKE_UP_Pin                   GPIO_PIN_0
#define DI_WAKE_UP_GPIO_Port             GPIOA
#define ETH_REF_CLK_Pin                  GPIO_PIN_1
#define ETH_REF_CLK_GPIO_Port            GPIOA
#define ETH_MDIO_Pin                     GPIO_PIN_2
#define ETH_MDIO_GPIO_Port               GPIOA
#define ADC1_IN3_Pin                     GPIO_PIN_3
#define ADC1_IN3_GPIO_Port               GPIOA
#define ADC1_IN4_Pin                     GPIO_PIN_4
#define ADC1_IN4_GPIO_Port               GPIOA
#define DO_CON_PWR_RAIN_Pin              GPIO_PIN_5
#define DO_CON_PWR_RAIN_GPIO_Port        GPIOA
#define DI_RAIN_INT_H_Pin                GPIO_PIN_6
#define DI_RAIN_INT_H_GPIO_Port          GPIOA
#define ETH_CRS_DV_Pin                   GPIO_PIN_7
#define ETH_CRS_DV_GPIO_Port             GPIOA
#define USB_OTG_FS_SOF_Pin               GPIO_PIN_8
#define USB_OTG_FS_SOF_GPIO_Port         GPIOA
#define USB_OTG_FS_VBUS_Pin              GPIO_PIN_9
#define USB_OTG_FS_VBUS_GPIO_Port        GPIOA
#define USB_OTG_FS_ID_Pin                GPIO_PIN_10
#define USB_OTG_FS_ID_GPIO_Port          GPIOA
#define USB_OTG_FS_DM_Pin                GPIO_PIN_11
#define USB_OTG_FS_DM_GPIO_Port          GPIOA
#define USB_OTG_FS_DP_Pin                GPIO_PIN_12
#define USB_OTG_FS_DP_GPIO_Port          GPIOA
#define SYS_JTMS_SWDIO_Pin               GPIO_PIN_13
#define SYS_JTMS_SWDIO_GPIO_Port         GPIOA
#define SYS_JTCK_SWCLK_Pin               GPIO_PIN_14
#define SYS_JTCK_SWCLK_GPIO_Port         GPIOA
#define DO_SPI1_NSS_Pin                  GPIO_PIN_15
#define DO_SPI1_NSS_GPIO_Port            GPIOA

// PORTB pins
#define DI_INT_D_IO_Pin                  GPIO_PIN_0
#define DI_INT_D_IO_GPIO_Port            GPIOB
#define DI_RAIN_PULSE_H_Pin              GPIO_PIN_1
#define DI_RAIN_PULSE_H_GPIO_Port        GPIOB
#define DI_BOOT1_Pin                     GPIO_PIN_2
#define DI_BOOT1_GPIO_Port               GPIOB
#define SPI1_SCK_Pin                     GPIO_PIN_3
#define SPI1_SCK_GPIO_Port               GPIOB
#define SPI1_MISO_Pin                    GPIO_PIN_4
#define SPI1_MISO_GPIO_Port              GPIOB
#define SPI1_MOSI_Pin                    GPIO_PIN_5
#define SPI1_MOSI_GPIO_Port              GPIOB
#define I2C1_SCL_Pin                     GPIO_PIN_6
#define I2C1_SCL_GPIO_Port               GPIOB
#define I2C1_SDA_Pin                     GPIO_PIN_7
#define I2C1_SDA_GPIO_Port               GPIOB
#define USB_OTG_PWR_FAIL_Pin             GPIO_PIN_8
#define USB_OTG_PWR_FAIL_GPIO_Port       GPIOB
#define DO_SEL_IF_UART_Pin               GPIO_PIN_9
#define DO_SEL_IF_UART_GPIO_Port         GPIOB
#define UART3_TX_Pin                     GPIO_PIN_10
#define UART3_TX_GPIO_Port               GPIOB
#define UART3_RX_Pin                     GPIO_PIN_11
#define UART3_RX_GPIO_Port               GPIOB
#define ETH_TXD0_Pin                     GPIO_PIN_12
#define ETH_TXD0_GPIO_Port               GPIOB
#define ETH_TXD1_Pin                     GPIO_PIN_13
#define ETH_TXD1_GPIO_Port               GPIOB
#define DO_STATUS_BTM_Pin                GPIO_PIN_14
#define DO_STATUS_BTM_GPIO_Port          GPIOB
#define DO_BTM_PWRC_Pin                  GPIO_PIN_15
#define DO_BTM_PWRC_GPIO_Port            GPIOB

// PORTC pins
#define DO_CON_PWR_S24_Pin               GPIO_PIN_0
#define DO_CON_PWR_S24_GPIO_Port         GPIOC
#define ETH_MDC_Pin                      GPIO_PIN_1
#define ETH_MDC_GPIO_Port                GPIOC
#define DI_SPI2_DRDY_Pin                 GPIO_PIN_2
#define DI_SPI2_DRDY_GPIO_Port           GPIOC
#define DO_RS485_DIR_C_Pin               GPIO_PIN_3
#define DO_RS485_DIR_C_GPIO_Port         GPIOC
#define ETH_RXD0_Pin                     GPIO_PIN_4
#define ETH_RXD0_GPIO_Port               GPIOC
#define ETH_RXD1_Pin                     GPIO_PIN_5
#define ETH_RXD1_GPIO_Port               GPIOC
#define UART6_TX_Pin                     GPIO_PIN_6
#define UART6_TX_GPIO_Port               GPIOC
#define UART6_RX_Pin                     GPIO_PIN_7
#define UART6_RX_GPIO_Port               GPIOC
#define SDIO_D0_Pin                      GPIO_PIN_8
#define SDIO_D0_GPIO_Port                GPIOC
#define SDIO_D1_Pin                      GPIO_PIN_9
#define SDIO_D1_GPIO_Port                GPIOC
#define SDIO_D2_Pin                      GPIO_PIN_10
#define SDIO_D2_GPIO_Port                GPIOC
#define SDIO_D3_Pin                      GPIO_PIN_11
#define SDIO_D3_GPIO_Port                GPIOC
#define SDIO_CK_Pin                      GPIO_PIN_12
#define SDIO_CK_GPIO_Port                GPIOC
#define DI_RAIN_IN_Pin                   GPIO_PIN_13
#define DI_RAIN_IN_GPIO_Port             GPIOC

// PORTD pins
#define FSMC_D2_Pin                      GPIO_PIN_0
#define FSMC_D2_GPIO_Port                GPIOD
#define FSMC_D3_Pin                      GPIO_PIN_1
#define FSMC_D3_GPIO_Port                GPIOD
#define SDIO_CMD_Pin                     GPIO_PIN_2
#define SDIO_CMD_GPIO_Port               GPIOD
#define DI_SDIO_DETECT_Pin               GPIO_PIN_3
#define DI_SDIO_DETECT_GPIO_Port         GPIOD
#define FSMC_NOE_Pin                     GPIO_PIN_4
#define FSMC_NOE_GPIO_Port               GPIOD
#define FSMC_NWE_Pin                     GPIO_PIN_5
#define FSMC_NWE_GPIO_Port               GPIOD
#define DO_R_RAIN_DECT_Pin               GPIO_PIN_6
#define DO_R_RAIN_DECT_GPIO_Port         GPIOD
#define FSMC_NE1_Pin                     GPIO_PIN_7
#define FSMC_NE1_GPIO_Port               GPIOD
#define FSMC_D13_Pin                     GPIO_PIN_8
#define FSMC_D13_GPIO_Port               GPIOD
#define FSMC_D14_Pin                     GPIO_PIN_9
#define FSMC_D14_GPIO_Port               GPIOD
#define FSMC_D15_Pin                     GPIO_PIN_10
#define FSMC_D15_GPIO_Port               GPIOD
#define FSMC_A16_Pin                     GPIO_PIN_11
#define FSMC_A16_GPIO_Port               GPIOD
#define FSMC_A17_Pin                     GPIO_PIN_12
#define FSMC_A17_GPIO_Port               GPIOD
#define FSMC_A18_Pin                     GPIO_PIN_13
#define FSMC_A18_GPIO_Port               GPIOD
#define FSMC_D0_Pin                      GPIO_PIN_14
#define FSMC_D0_GPIO_Port                GPIOD
#define FSMC_D1_Pin                      GPIO_PIN_15
#define FSMC_D1_GPIO_Port                GPIOD

// PORTE pins
#define FSMC_NBL0_Pin                    GPIO_PIN_0
#define FSMC_NBL0_GPIO_Port              GPIOE
#define FSMC_NBL1_Pin                    GPIO_PIN_1
#define FSMC_NBL1_GPIO_Port              GPIOE
#define DO_EX_UART_RST_A_Pin             GPIO_PIN_2
#define DO_EX_UART_RST_A_GPIO_Port       GPIOE
#define FSMC_A19_Pin                     GPIO_PIN_3
#define FSMC_A19_GPIO_Port               GPIOE
#define FSMC_A20_Pin                     GPIO_PIN_4
#define FSMC_A20_GPIO_Port               GPIOE
#define DO_SPI1_CS_RTC_Pin               GPIO_PIN_5
#define DO_SPI1_CS_RTC_GPIO_Port         GPIOE
#define DO_EX_UART_RST_B_Pin             GPIO_PIN_6
#define DO_EX_UART_RST_B_GPIO_Port       GPIOE
#define FSMC_D4_Pin                      GPIO_PIN_7
#define FSMC_D4_GPIO_Port                GPIOE
#define FSMC_D5_Pin                      GPIO_PIN_8
#define FSMC_D5_GPIO_Port                GPIOE
#define FSMC_D6_Pin                      GPIO_PIN_9
#define FSMC_D6_GPIO_Port                GPIOE
#define FSMC_D7_Pin                      GPIO_PIN_10
#define FSMC_D7_GPIO_Port                GPIOE
#define FSMC_D8_Pin                      GPIO_PIN_11
#define FSMC_D8_GPIO_Port                GPIOE
#define FSMC_D9_Pin                      GPIO_PIN_12
#define FSMC_D9_GPIO_Port                GPIOE
#define FSMC_D10_Pin                     GPIO_PIN_13
#define FSMC_D10_GPIO_Port               GPIOE
#define FSMC_D11_Pin                     GPIO_PIN_14
#define FSMC_D11_GPIO_Port               GPIOE
#define FSMC_D12_Pin                     GPIO_PIN_15
#define FSMC_D12_GPIO_Port               GPIOE

// PORTF pins
#define FSMC_A0_Pin                      GPIO_PIN_0
#define FSMC_A0_GPIO_Port                GPIOF
#define FSMC_A1_Pin                      GPIO_PIN_1
#define FSMC_A1_GPIO_Port                GPIOF
#define FSMC_A2_Pin                      GPIO_PIN_2
#define FSMC_A2_GPIO_Port                GPIOF
#define FSMC_A3_Pin                      GPIO_PIN_3
#define FSMC_A3_GPIO_Port                GPIOF
#define FSMC_A4_Pin                      GPIO_PIN_4
#define FSMC_A4_GPIO_Port                GPIOF
#define FSMC_A5_Pin                      GPIO_PIN_5
#define FSMC_A5_GPIO_Port                GPIOF
#define TIM10_CH1_Pin                    GPIO_PIN_6
#define TIM10_CH1_GPIO_Port              GPIOF
#define TIM11_CH1_Pin                    GPIO_PIN_7
#define TIM11_CH1_GPIO_Port              GPIOF
#define DO_/RESET_H_Pin                  GPIO_PIN_8
#define DO_/RESET_H_GPIO_Port            GPIOF
#define DO_RTS_H_Pin                     GPIO_PIN_9
#define DO_RTS_H_GPIO_Port               GPIOF
#define DI_CD_H_Pin                      GPIO_PIN_10
#define DI_CD_H_GPIO_Port                GPIOF
#define DO_RS485_DIR_D_Pin               GPIO_PIN_11
#define DO_RS485_DIR_D_GPIO_Port         GPIOF
#define FSMC_A6_Pin                      GPIO_PIN_12
#define FSMC_A6_GPIO_Port                GPIOF
#define FSMC_A7_Pin                      GPIO_PIN_13
#define FSMC_A7_GPIO_Port                GPIOF
#define FSMC_A8_Pin                      GPIO_PIN_14
#define FSMC_A8_GPIO_Port                GPIOF
#define FSMC_A9_Pin                      GPIO_PIN_15
#define FSMC_A9_GPIO_Port                GPIOF

// PORTG pins
#define FSMC_A10_Pin                     GPIO_PIN_0
#define FSMC_A10_GPIO_Port               GPIOG
#define FSMC_A11_Pin                     GPIO_PIN_1
#define FSMC_A11_GPIO_Port               GPIOG
#define FSMC_A12_Pin                     GPIO_PIN_2
#define FSMC_A12_GPIO_Port               GPIOG
#define FSMC_A13_Pin                     GPIO_PIN_3
#define FSMC_A13_GPIO_Port               GPIOG
#define FSMC_A14_Pin                     GPIO_PIN_4
#define FSMC_A14_GPIO_Port               GPIOG
#define FSMC_A15_Pin                     GPIO_PIN_5
#define FSMC_A15_GPIO_Port               GPIOG
#define DO_DIR_RS485_A_Pin               GPIO_PIN_6
#define DO_DIR_RS485_A_GPIO_Port         GPIOG
#define DO_DIR_RS485_B_Pin               GPIO_PIN_7
#define DO_DIR_RS485_B_GPIO_Port         GPIOG
#define DO_DIR_SDI_Pin                   GPIO_PIN_8
#define DO_DIR_SDI_GPIO_Port             GPIOG
#define FSMC_NE2_Pin                     GPIO_PIN_9
#define FSMC_NE2_GPIO_Port               GPIOG
#define FSMC_NE3_Pin                     GPIO_PIN_10
#define FSMC_NE3_GPIO_Port               GPIOG
#define ETH_TX_EN_Pin                    GPIO_PIN_11
#define ETH_TX_EN_GPIO_Port              GPIOG
#define DI_SW_SYS_Pin                    GPIO_PIN_12
#define DI_SW_SYS_GPIO_Port              GPIOG
#define DO_NOR_RESET_Pin                 GPIO_PIN_13
#define DO_NOR_RESET_GPIO_Port           GPIOG
#define DI_INT_RTC_Pin                   GPIO_PIN_14
#define DI_INT_RTC_GPIO_Port             GPIOG
#define DI_RAIN_DETECT_Pin               GPIO_PIN_15
#define DI_RAIN_DETECT_GPIO_Port         GPIOG

// PORTH pins
#define ETH_RST_PHY_Pin                  GPIO_PIN_2
#define ETH_RST_PHY_GPIO_Port            GPIOH
#define ETH_RX_ER_Pin                    GPIO_PIN_3
#define ETH_RX_ER_GPIO_Port              GPIOH
#define I2C2_SCL_Pin                     GPIO_PIN_4
#define I2C2_SCL_GPIO_Port               GPIOH
#define I2C2_SDA_Pin                     GPIO_PIN_5
#define I2C2_SDA_GPIO_Port               GPIOH
#define DO_CON_PWR_CDMA_Pin              GPIO_PIN_6
#define DO_CON_PWR_CDMA_GPIO_Port        GPIOH
#define I2C3_SCL_Pin                     GPIO_PIN_7
#define I2C3_SCL_GPIO_Port               GPIOH
#define DO_I2C3_SDA_Pin                  GPIO_PIN_8
#define DO_I2C3_SDA_GPIO_Port            GPIOH
#define DO_SYS_RUN_Pin                   GPIO_PIN_9
#define DO_SYS_RUN_GPIO_Port             GPIOH
#define DO_ADC_EN_RTD_Pin                GPIO_PIN_10
#define DO_ADC_EN_RTD_GPIO_Port          GPIOH
#define DO_ADC_EN_ODD_Pin                GPIO_PIN_11
#define DO_ADC_EN_ODD_GPIO_Port          GPIOH
#define DO_ADC_EN_EVEN_Pin               GPIO_PIN_12
#define DO_ADC_EN_EVEN_GPIO_Port         GPIOH
#define DO_ADC_SEL_A0_Pin                GPIO_PIN_13
#define DO_ADC_SEL_A0_GPIO_Port          GPIOH
#define DO_ADC_SEL_A1_Pin                GPIO_PIN_14
#define DO_ADC_SEL_A1_GPIO_Port          GPIOH
#define DO_ADC_SEL_A2_Pin                GPIO_PIN_15
#define DO_ADC_SEL_A2_GPIO_Port          GPIOH

// PORTI pins
#define DO_SPI2_NSS_Pin                  GPIO_PIN_0
#define DO_SPI2_NSS_GPIO_Port            GPIOI
#define SPI2_SCK_Pin                     GPIO_PIN_1
#define SPI2_SCK_GPIO_Port               GPIOI
#define SPI2_MISO_Pin                    GPIO_PIN_2
#define SPI2_MISO_GPIO_Port              GPIOI
#define SPI2_MOSI_Pin                    GPIO_PIN_3
#define SPI2_MOSI_GPIO_Port              GPIOI
#define DI_EX_UART_INT1_Pin              GPIO_PIN_4
#define DI_EX_UART_INT1_GPIO_Port        GPIOI
#define DI_EX_UART_INT2_Pin              GPIO_PIN_5
#define DI_EX_UART_INT2_GPIO_Port        GPIOI
#define DI_EX_UART_INT3_Pin              GPIO_PIN_6
#define DI_EX_UART_INT3_GPIO_Port        GPIOI
#define DI_EX_UART_INT4_Pin              GPIO_PIN_7
#define DI_EX_UART_INT4_GPIO_Port        GPIOI
#define DI_EX_UART_INT5_Pin              GPIO_PIN_8
#define DI_EX_UART_INT5_GPIO_Port        GPIOI
#define DI_EX_UART_INT6_Pin              GPIO_PIN_9
#define DI_EX_UART_INT6_GPIO_Port        GPIOI
#define DI_EX_UART_INT7_Pin              GPIO_PIN_10
#define DI_EX_UART_INT7_GPIO_Port        GPIOI
#define DI_EX_UART_INT8_Pin              GPIO_PIN_11
#define DI_EX_UART_INT8_GPIO_Port        GPIOI

#endif /* PCB_PIN_MAP_H */