
#ifndef TASK_MENU_DEFINE_H
#define TASK_MENU_DEFINE_H

#define TASK_MENU_ALARM_ALERT 0x01
#define TASK_MENU_ALARM_UPDATE 0x02
#define TASK_MENU_ALARM_FILE_RET_OK 0x04
#define TASK_MENU_ALARM_FILE_RET_FAIL 0x08

#endif