

#ifndef AWS_DEFAULT_DATA_H
#define AWS_DEFAULT_DATA_H

#include <stdint.h>

typedef enum avg_1min_e
{
  eAVG_TEMPERATURE,
  eAVG_RELATIVE_HUMIDITY,
  eAVG_PRESSURE,
  eAVG_GROUND_TEMPERATURE,
  eAVG_SURFACE_TEMPERATURE,
  eAVG_SOIL_TEMPERATURE_5CM,
  eAVG_SOIL_TEMPERATURE_10CM,
  eAVG_SOIL_TEMPERATURE_20CM,
  eAVG_SOIL_TEMPERATURE_30CM,
  eAVG_SOIL_TEMPERATURE_50CM,
  eAVG_SOIL_TEMPERATURE_100CM,
  eAVG_SOIL_TEMPERATURE_150CM,
  eAVG_SOIL_TEMPERATURE_300CM,
  eAVG_SOIL_TEMPERATURE_500CM,
  eAVG_MAX
} eAVG_1MIN_TYPE_t;

void add_sample_1min(eAVG_1MIN_TYPE_t number, int32_t data);
void calculate_1min_avg(eAVG_1MIN_TYPE_t number, int32_t *p_avg);
#endif
